### ISSUE TITLE
Add slice-n-dice UI

### ISSUE THREAD

**Issue by FilomenoSanchez** [moorhen-coot/Moorhen#352]
Now that we have slice-n-dice available in `molecules_container_js` it should be possible to have this exposed in the UI. This is required:

- [x] ~~Add menu item button within Calculate named "slice-n-dice". Open a slice-n-dice draggable modal on click.~~ Done in #360
- [x] ~~The UI to set the input parameters for slice-n-dice is within this draggable modal. Required input fields: clustering algorithm, input molecule, no. of clusters...etc.~~ Done in #360
- [x] ~~Apply button should run clustering algorithm. Perhaps a better implementation would be to run it automatically when all the inputs have been provided, depends on how long it takes. The resulting clusters are drawn as separate molecules with separate colours.~~ Done in #360
- [x] ~~Some information about each cluster should be given and there should be some action buttons (number of atoms, center on model, download button...etc).~~ Done in #360
- [x] ~~There should be buttons to download each separate cluster, all clusters at once and all clusters as an ensemble. Probably a dropdown github style.~~ Done in #360
- [x] ~~There should be a button to commit the changes into the session. This will create a separate `MoorhenMolecule` for each cluster and add them to `molecules_container`.~~ Done in https://github.com/moorhen-coot/Moorhen/commit/cea07ff85dc37742823c85c3a9a0f31472de9e92

This should be available both in stand-alone moorhen and search model preparation mode in CCP4 Cloud.
